/**
 * Lore Bundle - Auto-generated by compile-lore.ts
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * Generated: 2025-10-21T02:19:43.470Z
 * Lore Version: 2025.10.18
 * Rules Hash: c3f7dd2f1f21f508
 */

import type { LoreBundle } from './schemas';

export const loreBundle: LoreBundle = {
  "lore_version": "2025.10.18",
  "tieThresholdPct": 6,
  "rules_hash": "c3f7dd2f1f21f508",
  "systems": [
    {
      "id": "ANDROMEDA",
      "label": "Andromeda",
      "description": "Explorers, iconoclasts; freedom, innovation, boundary breaking."
    },
    {
      "id": "ARCTURUS",
      "label": "Arcturus",
      "description": "Engineers, healers, pattern architects; mind–heart coherence, clean geometry."
    },
    {
      "id": "DRACO",
      "label": "Draco",
      "description": "Power, will, hierarchy; alchemy of desire/ambition (highly disputed/charged lore)."
    },
    {
      "id": "LYRA",
      "label": "Lyra",
      "description": "Primordial builders; instinct, courage, survival wisdom, sovereignty."
    },
    {
      "id": "ORION",
      "label": "Orion",
      "description": "Strategists, historians; polarity integration, memory, trial by conflict."
    },
    {
      "id": "PLEIADES",
      "label": "Pleiades",
      "description": "Nurturers, artists, empaths; joy, sensuality, community weaving."
    },
    {
      "id": "SIRIUS",
      "label": "Sirius",
      "description": "Teachers, guardians, priestly orders; voice, ritual, stewardship, waters."
    },
    {
      "id": "ZETA",
      "label": "Zeta Reticuli",
      "description": "Analysts, experimenters; abstraction, detached observation, adaptation."
    }
  ],
  "sources": [
    {
      "id": "s-anka-1990",
      "title": "Bashar Transmissions",
      "author": "Darryl Anka",
      "year": 1990,
      "disputed": true
    },
    {
      "id": "s-cannon-1994",
      "title": "Keepers of the Garden",
      "author": "Dolores Cannon",
      "year": 1994,
      "disputed": true
    },
    {
      "id": "s-collier-1994",
      "title": "Andromedan material",
      "author": "Alex Collier",
      "year": 1994,
      "disputed": true
    },
    {
      "id": "s-handclow-1995",
      "title": "The Pleiadian Agenda",
      "author": "Barbara Hand Clow",
      "year": 1995,
      "disputed": true
    },
    {
      "id": "s-marciniak-1992",
      "title": "Bringers of the Dawn",
      "author": "Barbara Marciniak",
      "year": 1992,
      "disputed": true
    },
    {
      "id": "s-pan-oral",
      "title": "Pan-human esoteric/oral syntheses",
      "author": "Various",
      "year": 1900,
      "disputed": true
    },
    {
      "id": "s-ra-1984",
      "title": "The Law of One (Ra Material), Book I",
      "author": "L/L Research",
      "year": 1984,
      "disputed": false
    },
    {
      "id": "s-royal-1992",
      "title": "Prism of Lyra",
      "author": "Lyssa Royal & Keith Priest",
      "year": 1992,
      "disputed": true
    }
  ],
  "rules": [
    {
      "id": "auth_ego_draco",
      "systems": [
        {
          "id": "DRACO",
          "w": 1.8
        }
      ],
      "if": {
        "authorityAny": [
          "Ego"
        ]
      },
      "rationale": "Will/contract energy; hierarchy & oath (useful or coercive).",
      "sources": [
        "s-royal-1992"
      ],
      "confidence": 1
    },
    {
      "id": "auth_emotional_sirius_pleiades",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 1.4
        },
        {
          "id": "PLEIADES",
          "w": 0.9
        }
      ],
      "if": {
        "authorityAny": [
          "Emotional"
        ]
      },
      "rationale": "Tidal wisdom & empathy; priestly pacing of waves.",
      "sources": [
        "s-ra-1984",
        "s-handclow-1995"
      ],
      "confidence": 2
    },
    {
      "id": "auth_lunar_zeta",
      "systems": [
        {
          "id": "ZETA",
          "w": 1.5
        }
      ],
      "if": {
        "authorityAny": [
          "Lunar"
        ]
      },
      "rationale": "Cyclic sampling; adaptive neutrality.",
      "sources": [
        "s-anka-1990"
      ],
      "confidence": 1
    },
    {
      "id": "auth_mental_arcturus",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1.8
        }
      ],
      "if": {
        "authorityAny": [
          "Mental"
        ]
      },
      "rationale": "Clean geometry; pattern stabilization.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 2
    },
    {
      "id": "auth_sacral_pleiades",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 1.6
        }
      ],
      "if": {
        "authorityAny": [
          "Sacral"
        ]
      },
      "rationale": "Joy-response, craft, fertility lines.",
      "sources": [
        "s-marciniak-1992"
      ],
      "confidence": 2
    },
    {
      "id": "auth_self_andromeda",
      "systems": [
        {
          "id": "ANDROMEDA",
          "w": 1.6
        }
      ],
      "if": {
        "authorityAny": [
          "Self",
          "Self-Projected"
        ]
      },
      "rationale": "Freedom-pathfinding through voice & direction.",
      "sources": [
        "s-collier-1994"
      ],
      "confidence": 2
    },
    {
      "id": "auth_splenic_lyra",
      "systems": [
        {
          "id": "LYRA",
          "w": 1.8
        }
      ],
      "if": {
        "authorityAny": [
          "Splenic"
        ]
      },
      "rationale": "Primal instinct & body-knowing; survival elegance.",
      "sources": [
        "s-royal-1992",
        "s-pan-oral"
      ],
      "confidence": 3
    },
    {
      "id": "center_ajna_arcturus_zeta",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1
        },
        {
          "id": "ZETA",
          "w": 0.7
        }
      ],
      "if": {
        "centersAny": [
          "Ajna"
        ]
      },
      "rationale": "Pattern encoding; analytic abstraction.",
      "sources": [
        "s-anka-1990",
        "s-ra-1984"
      ],
      "confidence": 2
    },
    {
      "id": "center_ego_draco",
      "systems": [
        {
          "id": "DRACO",
          "w": 1.1
        }
      ],
      "if": {
        "centersAny": [
          "Ego"
        ]
      },
      "rationale": "Will/contract; sovereignty shadows.",
      "sources": [
        "s-royal-1992"
      ],
      "confidence": 1
    },
    {
      "id": "center_g_pleiades",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 1.1
        }
      ],
      "if": {
        "centersAny": [
          "G"
        ]
      },
      "rationale": "Love, direction, harmonic bonding.",
      "sources": [
        "s-marciniak-1992"
      ],
      "confidence": 2
    },
    {
      "id": "center_solar_plexus_sirius_pleiades",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 0.9
        },
        {
          "id": "PLEIADES",
          "w": 0.9
        }
      ],
      "if": {
        "centersAny": [
          "Solar Plexus"
        ]
      },
      "rationale": "Emotional tides; devotion and art.",
      "sources": [
        "s-handclow-1995",
        "s-ra-1984"
      ],
      "confidence": 2
    },
    {
      "id": "center_spleen_lyra",
      "systems": [
        {
          "id": "LYRA",
          "w": 1.2
        }
      ],
      "if": {
        "centersAny": [
          "Spleen"
        ]
      },
      "rationale": "Instinct & survival clarity.",
      "sources": [
        "s-royal-1992"
      ],
      "confidence": 3
    },
    {
      "id": "center_throat_sirius",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 1.2
        }
      ],
      "if": {
        "centersAny": [
          "Throat"
        ]
      },
      "rationale": "Voice, ritual speech, decree.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3
    },
    {
      "id": "ch_1_8_andromeda_creator",
      "systems": [
        {
          "id": "ANDROMEDA",
          "w": 1.3
        }
      ],
      "if": {
        "channelsAny": [
          "1-8"
        ]
      },
      "rationale": "Creative direction amplified by contribution.",
      "sources": [
        "s-collier-1994"
      ],
      "confidence": 2,
      "synergy": true
    },
    {
      "id": "ch_7_31_sirius_steward",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 1.4
        }
      ],
      "if": {
        "channelsAny": [
          "7-31"
        ]
      },
      "rationale": "From will of the self to voice of the people; council leadership.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3,
      "synergy": true
    },
    {
      "id": "ch_10_20_lyra_awakened_action",
      "systems": [
        {
          "id": "LYRA",
          "w": 1
        },
        {
          "id": "SIRIUS",
          "w": 0.6
        }
      ],
      "if": {
        "channelsAny": [
          "10-20"
        ]
      },
      "rationale": "Awakened behavior expressed in real-time action.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 2,
      "synergy": true
    },
    {
      "id": "ch_13_33_orion_historians",
      "systems": [
        {
          "id": "ORION",
          "w": 1.6
        }
      ],
      "if": {
        "channelsAny": [
          "13-33"
        ]
      },
      "rationale": "Collective memory → retreat → archivist historian.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3,
      "synergy": true
    },
    {
      "id": "ch_19_49_pleiades_ethic",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 1
        },
        {
          "id": "LYRA",
          "w": 0.6
        }
      ],
      "if": {
        "channelsAny": [
          "19-49"
        ]
      },
      "rationale": "Sensitivity → principles; communal bonds with backbone.",
      "sources": [
        "s-handclow-1995",
        "s-royal-1992"
      ],
      "confidence": 2,
      "synergy": true
    },
    {
      "id": "ch_20_34_draco_power",
      "systems": [
        {
          "id": "DRACO",
          "w": 1.3
        },
        {
          "id": "LYRA",
          "w": 0.5
        }
      ],
      "if": {
        "channelsAny": [
          "20-34"
        ]
      },
      "rationale": "Charisma + power-in-the-now; demands heart ethics.",
      "sources": [
        "s-royal-1992"
      ],
      "confidence": 1,
      "synergy": true
    },
    {
      "id": "ch_32_54_orion_ambition",
      "systems": [
        {
          "id": "ORION",
          "w": 1
        },
        {
          "id": "DRACO",
          "w": 0.9
        }
      ],
      "if": {
        "channelsAny": [
          "32-54"
        ]
      },
      "rationale": "Legacy transformation fueled by drive.",
      "sources": [
        "s-royal-1992",
        "s-pan-oral"
      ],
      "confidence": 1,
      "synergy": true
    },
    {
      "id": "ch_43_23_arcturus_structurer",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1.4
        }
      ],
      "if": {
        "channelsAny": [
          "43-23"
        ]
      },
      "rationale": "Insight to articulation; engineering the novel.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3,
      "synergy": true
    },
    {
      "id": "ch_59_6_pleiades_bond",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 1.4
        }
      ],
      "if": {
        "channelsAny": [
          "59-6"
        ]
      },
      "rationale": "Bonding/intimacy regulating closeness.",
      "sources": [
        "s-marciniak-1992"
      ],
      "confidence": 2,
      "synergy": true
    },
    {
      "id": "ch_61_24_arcturus_mystic_mind",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1.2
        }
      ],
      "if": {
        "channelsAny": [
          "61-24"
        ]
      },
      "rationale": "Mystery processing loop → stabilized knowing.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3,
      "synergy": true
    },
    {
      "id": "gate_1_creative_andromeda",
      "systems": [
        {
          "id": "ANDROMEDA",
          "w": 1.2
        }
      ],
      "if": {
        "gatesAny": [
          1
        ]
      },
      "rationale": "Pure creative thrust; originality.",
      "sources": [
        "s-collier-1994"
      ],
      "confidence": 2
    },
    {
      "id": "gate_2_direction_pleiades",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 1
        }
      ],
      "if": {
        "gatesAny": [
          2
        ]
      },
      "rationale": "Receptive guidance, earth-mother vector.",
      "sources": [
        "s-marciniak-1992"
      ],
      "confidence": 2
    },
    {
      "id": "gate_7_leadership_sirius",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 1.1
        }
      ],
      "if": {
        "gatesAny": [
          7
        ]
      },
      "rationale": "Councils and stewardship.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3
    },
    {
      "id": "gate_10_self_behavior_lyra",
      "systems": [
        {
          "id": "LYRA",
          "w": 1
        }
      ],
      "if": {
        "gatesAny": [
          10
        ]
      },
      "rationale": "Courageous embodiment; natural law.",
      "sources": [
        "s-royal-1992"
      ],
      "confidence": 2
    },
    {
      "id": "gate_13_listener_orion",
      "systems": [
        {
          "id": "ORION",
          "w": 1.1
        }
      ],
      "if": {
        "gatesAny": [
          13
        ]
      },
      "rationale": "Keeper of stories; collective memory.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3
    },
    {
      "id": "gate_22_grace_sirius",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 0.9
        }
      ],
      "if": {
        "gatesAny": [
          22
        ]
      },
      "rationale": "Aesthetic presence; courtly arts.",
      "sources": [
        "s-pan-oral"
      ],
      "confidence": 1
    },
    {
      "id": "gate_33_retreat_orion",
      "systems": [
        {
          "id": "ORION",
          "w": 1
        }
      ],
      "if": {
        "gatesAny": [
          33
        ]
      },
      "rationale": "Archivist; withdrawal to consolidate memory.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3
    },
    {
      "id": "gate_34_power_draco",
      "systems": [
        {
          "id": "DRACO",
          "w": 1.2
        }
      ],
      "if": {
        "gatesAny": [
          34
        ]
      },
      "rationale": "Raw power & autonomy (needs heart alignment).",
      "sources": [
        "s-royal-1992"
      ],
      "confidence": 1
    },
    {
      "id": "gate_44_alert_lyra_orion",
      "systems": [
        {
          "id": "LYRA",
          "w": 0.9
        },
        {
          "id": "ORION",
          "w": 0.6
        }
      ],
      "if": {
        "gatesAny": [
          44
        ]
      },
      "rationale": "Instinctive pattern-recognition; ancestral memory.",
      "sources": [
        "s-royal-1992",
        "s-ra-1984"
      ],
      "confidence": 2
    },
    {
      "id": "gate_48_depth_arcturus",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1.1
        }
      ],
      "if": {
        "gatesAny": [
          48
        ]
      },
      "rationale": "Well of solutions; engineering depth.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3
    },
    {
      "id": "gate_51_shock_andromeda",
      "systems": [
        {
          "id": "ANDROMEDA",
          "w": 1
        }
      ],
      "if": {
        "gatesAny": [
          51
        ]
      },
      "rationale": "Catalyst/threshold-jumper; disruption to new freedom.",
      "sources": [
        "s-collier-1994"
      ],
      "confidence": 2
    },
    {
      "id": "gate_54_ambition_orion_draco",
      "systems": [
        {
          "id": "ORION",
          "w": 0.9
        },
        {
          "id": "DRACO",
          "w": 0.9
        }
      ],
      "if": {
        "gatesAny": [
          54
        ]
      },
      "rationale": "Drive to rise; transforms shadow desire into service.",
      "sources": [
        "s-royal-1992",
        "s-pan-oral"
      ],
      "confidence": 1
    },
    {
      "id": "gate_55_spirit_pleiades_sirius",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 0.8
        },
        {
          "id": "SIRIUS",
          "w": 0.7
        }
      ],
      "if": {
        "gatesAny": [
          55
        ]
      },
      "rationale": "Romance with life, mood alchemy, devotional ecstasy.",
      "sources": [
        "s-handclow-1995"
      ],
      "confidence": 2
    },
    {
      "id": "gate_59_intimacy_pleiades",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 1.1
        }
      ],
      "if": {
        "gatesAny": [
          59
        ]
      },
      "rationale": "Fertility/bonding; sensual bridge-builder.",
      "sources": [
        "s-marciniak-1992"
      ],
      "confidence": 2
    },
    {
      "id": "gate_61_mystery_arcturus",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1
        }
      ],
      "if": {
        "gatesAny": [
          61
        ]
      },
      "rationale": "Inner truth/mystery; clean noetic inquiry.",
      "sources": [
        "s-ra-1984"
      ],
      "confidence": 3
    },
    {
      "id": "gate_62_details_zeta",
      "systems": [
        {
          "id": "ZETA",
          "w": 1
        }
      ],
      "if": {
        "gatesAny": [
          62
        ]
      },
      "rationale": "Precise labeling; operational language.",
      "sources": [
        "s-anka-1990"
      ],
      "confidence": 2
    },
    {
      "id": "gate_63_doubt_arcturus_zeta",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 0.8
        },
        {
          "id": "ZETA",
          "w": 0.6
        }
      ],
      "if": {
        "gatesAny": [
          63
        ]
      },
      "rationale": "Skepticism/tests that refine patterns.",
      "sources": [
        "s-ra-1984",
        "s-anka-1990"
      ],
      "confidence": 2
    },
    {
      "id": "profile_1_investigator_arcturus_orion",
      "systems": [
        {
          "id": "ARCTURUS",
          "w": 1.2
        },
        {
          "id": "ORION",
          "w": 0.8
        }
      ],
      "if": {
        "profileAny": [
          "1/3",
          "1/4",
          "4/1",
          "5/1"
        ]
      },
      "rationale": "Foundational research; archive/record line.",
      "sources": [
        "s-ra-1984",
        "s-royal-1992"
      ],
      "confidence": 2
    },
    {
      "id": "profile_3_experimenter_andromeda",
      "systems": [
        {
          "id": "ANDROMEDA",
          "w": 1.4
        }
      ],
      "if": {
        "profileAny": [
          "1/3",
          "3/5",
          "3/6",
          "6/3"
        ]
      },
      "rationale": "Trial-and-error explorers.",
      "sources": [
        "s-collier-1994"
      ],
      "confidence": 2
    },
    {
      "id": "profile_5_heretic_sirius_draco",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 1
        },
        {
          "id": "DRACO",
          "w": 0.6
        }
      ],
      "if": {
        "profileAny": [
          "2/5",
          "3/5",
          "5/1",
          "5/2",
          "6/2"
        ]
      },
      "rationale": "Projection field leadership (service vs. control).",
      "sources": [
        "s-ra-1984",
        "s-royal-1992"
      ],
      "confidence": 1
    },
    {
      "id": "profile_6_rolemodel_pleiades_lyra",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 0.9
        },
        {
          "id": "LYRA",
          "w": 0.9
        }
      ],
      "if": {
        "profileAny": [
          "4/6",
          "6/2",
          "6/3"
        ]
      },
      "rationale": "Maturation arc; embodied wisdom.",
      "sources": [
        "s-handclow-1995",
        "s-pan-oral"
      ],
      "confidence": 2
    },
    {
      "id": "type_generator_pleiades",
      "systems": [
        {
          "id": "PLEIADES",
          "w": 2.5
        },
        {
          "id": "LYRA",
          "w": 0.5
        }
      ],
      "if": {
        "typeAny": [
          "Generator"
        ]
      },
      "rationale": "Generative life force (Sacral) → creative, communal cultivation; primordial craft lineages.",
      "sources": [
        "s-marciniak-1992",
        "s-royal-1992"
      ],
      "confidence": 2
    },
    {
      "id": "type_manifesting_generator_andromeda",
      "systems": [
        {
          "id": "ANDROMEDA",
          "w": 2
        },
        {
          "id": "PLEIADES",
          "w": 1
        }
      ],
      "if": {
        "typeAny": [
          "Manifesting Generator"
        ]
      },
      "rationale": "Hybrid speed + improvisation → explorer/innovator archetype; playful creation.",
      "sources": [
        "s-anka-1990",
        "s-royal-1992"
      ],
      "confidence": 2
    },
    {
      "id": "type_manifestor_orion_draco",
      "systems": [
        {
          "id": "ORION",
          "w": 1.6
        },
        {
          "id": "DRACO",
          "w": 1
        }
      ],
      "if": {
        "typeAny": [
          "Manifestor"
        ]
      },
      "rationale": "Initiation and will; command presence (shadow can skew to domination).",
      "sources": [
        "s-royal-1992",
        "s-pan-oral"
      ],
      "confidence": 2
    },
    {
      "id": "type_projector_sirius",
      "systems": [
        {
          "id": "SIRIUS",
          "w": 2.2
        },
        {
          "id": "ARCTURUS",
          "w": 0.8
        }
      ],
      "if": {
        "typeAny": [
          "Projector"
        ]
      },
      "rationale": "Guidance, attunement, ceremony; pattern-reading and counsel.",
      "sources": [
        "s-ra-1984",
        "s-pan-oral"
      ],
      "confidence": 3
    },
    {
      "id": "type_reflector_zeta_andromeda",
      "systems": [
        {
          "id": "ZETA",
          "w": 1.5
        },
        {
          "id": "ANDROMEDA",
          "w": 1
        }
      ],
      "if": {
        "typeAny": [
          "Reflector"
        ]
      },
      "rationale": "Sampling/reflecting fields; detached awareness and novelty-seeking.",
      "sources": [
        "s-anka-1990",
        "s-pan-oral"
      ],
      "confidence": 2
    }
  ]
} as const;

export default loreBundle;
