# Netlify configuration for Star System Sorter

[build]
  command = "npm run build"
  publish = "dist"

# Redirect API calls to Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/hd"
  status = 200

# SPA fallback - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
