#!/usr/bin/env python3
"""
Audit gate-line weights against v4.2 baseline standards.

Scans all gate files and reports violations of prescribed weight ranges:
- Core behaviors should be 0.7-1.0
- Shadow behaviors should be 0.4-0.6
- Weak flavors should be 0.1-0.3
- Non-matches should be ~0

Output: lore-research/research-outputs/WEIGHT_CALIBRATION_AUDIT.md
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Tuple
from collections import defaultdict

# Paths
SCRIPT_DIR = Path(__file__).parent
GATE_DIR = SCRIPT_DIR.parent / "research-outputs" / "star-mapping-by-gate"
OUTPUT_FILE = SCRIPT_DIR.parent / "research-outputs" / "WEIGHT_CALIBRATION_AUDIT.md"

# Weight standards from v4.2 baselines
WEIGHT_STANDARDS = {
    "core": {"min": 0.7, "max": 1.0, "label": "Core Match"},
    "shadow": {"min": 0.4, "max": 0.6, "label": "Shadow Expression"},
    "weak": {"min": 0.1, "max": 0.3, "label": "Weak Flavor"},
    "none": {"min": 0.0, "max": 0.05, "label": "Non-Match"},
}

SYSTEMS = [
    "andromeda",
    "arcturus", 
    "draco",
    "lyra",
    "orion-dark",
    "orion-light",
    "pleiades",
    "sirius",
]


def load_gate_file(gate_num: int) -> Dict:
    """Load a gate JSON file."""
    gate_file = GATE_DIR / f"gate-{gate_num}.json"
    if not gate_file.exists():
        return {}
    
    with open(gate_file, 'r', encoding='utf-8') as f:
        return json.load(f)


def analyze_weight(weight: float, alignment_type: str) -> Tuple[str, str]:
    """
    Analyze if weight matches expected range for alignment type.
    
    Returns: (status, issue_description)
    - status: "ok", "under", "over", "wrong_range"
    - issue_description: human-readable problem
    """
    if alignment_type == "core":
        if weight >= 0.7:
            return "ok", ""
        elif weight >= 0.4:
            return "under", f"Core behavior but weight={weight:.2f} (should be 0.7-1.0)"
        else:
            return "under", f"Core behavior but weight={weight:.2f} (severely under-weighted)"
    
    elif alignment_type == "shadow" or alignment_type == "secondary":
        if 0.4 <= weight <= 0.6:
            return "ok", ""
        elif weight < 0.4:
            return "under", f"Shadow behavior but weight={weight:.2f} (should be 0.4-0.6)"
        else:
            return "over", f"Shadow behavior but weight={weight:.2f} (should be 0.4-0.6)"
    
    elif alignment_type == "none":
        if weight <= 0.05:
            return "ok", ""
        else:
            return "over", f"Non-match but weight={weight:.2f} (should be ~0)"
    
    return "unknown", f"Unknown alignment_type: {alignment_type}"


def audit_all_gates() -> Dict[str, List[Dict]]:
    """
    Audit all gate files and collect violations by system.
    
    Returns: {system_name: [violations]}
    """
    violations_by_system = defaultdict(list)
    stats = defaultdict(lambda: {"total": 0, "violations": 0, "ok": 0})
    
    for gate_num in range(1, 65):
        gate_data = load_gate_file(gate_num)
        if not gate_data:
            continue
        
        for line_num in range(1, 7):
            gate_line_key = f"{gate_num}.{line_num}"
            line_data = gate_data.get(gate_line_key, {})
            
            for system in SYSTEMS:
                system_data = line_data.get(system, {})
                if not system_data:
                    continue
                
                weight = system_data.get("weight", 0)
                alignment_type = system_data.get("alignment_type", "none")
                why = system_data.get("why", "")
                
                stats[system]["total"] += 1
                
                status, issue = analyze_weight(weight, alignment_type)
                
                if status != "ok":
                    stats[system]["violations"] += 1
                    violations_by_system[system].append({
                        "gate_line": gate_line_key,
                        "weight": weight,
                        "alignment_type": alignment_type,
                        "why": why,
                        "issue": issue,
                        "status": status,
                    })
                else:
                    stats[system]["ok"] += 1
    
    return violations_by_system, stats


def generate_report(violations_by_system: Dict, stats: Dict) -> str:
    """Generate markdown report."""
    lines = [
        "# Weight Calibration Audit Report",
        "",
        "**Generated:** Auto-generated by 18-audit-weight-calibration.py",
        "**Purpose:** Identify gate-line weights that violate v4.2 baseline standards",
        "",
        "---",
        "",
        "## Summary Statistics",
        "",
        "| System | Total Lines | Violations | OK | Violation Rate |",
        "|--------|-------------|------------|----|-</s>--------------|",
    ]
    
    for system in SYSTEMS:
        s = stats[system]
        total = s["total"]
        viol = s["violations"]
        ok = s["ok"]
        rate = (viol / total * 100) if total > 0 else 0
        lines.append(f"| {system.title()} | {total} | {viol} | {ok} | {rate:.1f}% |")
    
    lines.extend([
        "",
        "---",
        "",
        "## Violations by System",
        "",
    ])
    
    for system in SYSTEMS:
        violations = violations_by_system[system]
        if not violations:
            continue
        
        lines.extend([
            f"### {system.title()}",
            "",
            f"**Total Violations:** {len(violations)}",
            "",
        ])
        
        # Group by status
        under = [v for v in violations if v["status"] == "under"]
        over = [v for v in violations if v["status"] == "over"]
        
        if under:
            lines.extend([
                "#### Under-Weighted",
                "",
            ])
            for v in under[:20]:  # Limit to first 20
                lines.extend([
                    f"**{v['gate_line']}** - {v['alignment_type']}",
                    f"- Weight: {v['weight']:.2f}",
                    f"- Why: {v['why'][:100]}...",
                    f"- Issue: {v['issue']}",
                    "",
                ])
            if len(under) > 20:
                lines.append(f"*... and {len(under) - 20} more under-weighted violations*\n")
        
        if over:
            lines.extend([
                "#### Over-Weighted",
                "",
            ])
            for v in over[:10]:  # Limit to first 10
                lines.extend([
                    f"**{v['gate_line']}** - {v['alignment_type']}",
                    f"- Weight: {v['weight']:.2f}",
                    f"- Why: {v['why'][:100]}...",
                    f"- Issue: {v['issue']}",
                    "",
                ])
            if len(over) > 10:
                lines.append(f"*... and {len(over) - 10} more over-weighted violations*\n")
        
        lines.append("---\n")
    
    lines.extend([
        "",
        "## Next Steps",
        "",
        "1. Review violations manually to determine:",
        "   - Which are genuine calibration errors",
        "   - Which are intentional (e.g., subtle flavors)",
        "   - Which represent wrong behavioral themes",
        "",
        "2. Create correction plan in this file (add annotations)",
        "",
        "3. Run `19-recalibrate-weights.py` to apply corrections",
        "",
    ])
    
    return "\n".join(lines)


def main():
    print("Auditing gate-line weights against v4.2 standards...")
    print(f"Reading from: {GATE_DIR}")
    
    violations_by_system, stats = audit_all_gates()
    
    print(f"\nFound violations:")
    for system in SYSTEMS:
        viol_count = len(violations_by_system[system])
        total = stats[system]["total"]
        if total > 0:
            print(f"  {system.title()}: {viol_count}/{total} ({viol_count/total*100:.1f}%)")
    
    report = generate_report(violations_by_system, stats)
    
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(report)
    
    print(f"\nReport written to: {OUTPUT_FILE}")
    print("\nNext: Review the report and annotate corrections needed.")


if __name__ == "__main__":
    main()
